### ISSUE TITLE
"No coverage" reported by extension while viewing PR whenever submitted and reported back just fine

### ISSUE THREAD

**Issue by yarikoptic** [codecov/browser-extension#22] opened 2016-03-07 17:52 UTC
See https://github.com/fail2ban/fail2ban/pull/1346/files for which codecov report is https://github.com/fail2ban/fail2ban/pull/1346#issuecomment-193358824  (I guess things might change whenever more commits are pushed into PR).  For me under both iceweasel (aka firefox, 44.0.2, codecov ext 0.4.6) and chromium (46.0.2490.71, codecov ext 0.5.8) on Debian stretch/sid all files have grayed out "No coverage" button, see e.g. http://www.onerussian.com/tmp/gkrellShoot_03-07-16_124934.png .

**Comment by par2** [comment] 2016-03-11 23:04
Getting a "Coverage Error"  on the Chrome Extension even on the default branch which hasn't seen recents commits.  https://github.com/par2/lamana/blob/develop/lamana/output_.py

**Comment by stevepeak** [comment] 2016-03-12 01:39
@par2 Looks like that link is now working :)

@yarikoptic This may be due to merge commits being used. I'll be fixing this soon https://github.com/codecov/support/issues/122

**Comment by par2** [comment] 2016-03-12 06:26
Thanks for the feedback.  Strange.  The extension works in another chrome profile, but not in my current one.  I'm unsure why it would suddenly stop in this profile.  

I suppose you can close this issue on my side.  Thanks.

**Comment by wilzbach** [comment] 2016-07-28 18:27
@stevepeak has the fix already been deployed?

First of all the browser extension is great - thanks a lot!
Unfortunately we seem to have an issue with at Phobos. While I can confirm that for first link in this thread & at [another library in D](https://github.com/libmir/mir/pull/239/files) the code coverage is found, & displayed, it doesn't seem to work yet with Phobos PRs. At least we get 404s - no coverage found despite the coverage report being there.

For example, when you look at this PR: https://github.com/dlang/phobos/pull/4674/files - the extension tries to find 539d860 (the non merge-commit hash) which as you can see fails.

In more detail, the merge-commit diff is highlighted:

https://github.com/dlang/phobos/commit/6db08d3dadb007d930a4042a6140ca4fb22ea540

However the exact commit isn't and shows: "No coverage found":

https://github.com/dlang/phobos/commit/539d860380edea250df7eb353174e58d8ef5f2cd

So I guess this is still the problem of merge-commits manifesting itself?

**Comment by par2** [comment] 2016-07-29 16:48
Issue still remains on my side.

**Comment by stevepeak** [comment] 2016-07-30 15:33
Duplicate to https://github.com/codecov/support/issues/263

Fixing today 🎉

**Closed by stevepeak** 2016-07-30 15:33 UTC
