### ISSUE TITLE
Coveralls info under Firefox

### ISSUE THREAD

**Issue by hhfrancois** [codecov/browser-extension#10] opened 2015-09-02 23:11 UTC
Hi, under firefox it seem that coverall coverage infos is added on the list file. 
When I move mouse, new values is added...
Under chrome, no problem

![capture d ecran 1](https://cloud.githubusercontent.com/assets/5840045/9646948/a9719228-51d8-11e5-964d-228dbfa55368.png)

**Comment by stevepeak** [comment] 2015-09-03 18:12
This issue will be resolved in an upcoming release. Caused by extension not removing past elements when new pjax requests came through.

**Comment by hhfrancois** [comment] 2015-09-03 18:22
Great, thx


2015-09-03 20:12 GMT+02:00 Steve Peak <notifications@github.com>:

**Comment by stevepeak** [comment] 2015-09-09 11:52
Fixes submitted to addon stores. Thank you!

**Closed by stevepeak** 2015-09-09 11:52 UTC
